export type Paths =
  | '/'
  | '/SiteMap'
  | '/ContractsList'
  | '/Contract'
  | '/ContractRegister'
  | '/StaffManager'
  | '/OtherDataImport'
  | '/AccessTotalling/'
  | '/AccessTotalling/Detail'
  | '/PopupNewsSetting'
  | '/Setting'
  | '/MasterSetting/ContractTypeSetting'
  | '/MasterSetting/FacilityTypeSetting'
  | '/MasterSetting/FacilityTypeGroupSetting'
  | '/MasterSetting/FeeStructureSetting';
