# 概要: 変数を管理するmakefile

# 入力値
VERSION = latest
ENVIRONMENT = develop
DOCKER_BASE_DIR = docker
DOCKER_IMAGE_NAME ?=
SERVICE_NAME ?=
SSM_PARAMETER_NAME ?=

# 固定値
DOCKER_IMAGE_TAG = ${VERSION}-${ENVIRONMENT}
DOCKER_CONTEXT_PATH := ${realpath ../../..}
DOCKER_FILE_PATH = ${DOCKER_BASE_DIR}/${ENVIRONMENT}/${DOCKER_IMAGE_NAME}/Dockerfile
DOCKER_FILE_FULL_PATH = ${DOCKER_CONTEXT_PATH}/${DOCKER_FILE_PATH}

TASK_FILE_PATH = makefiles
DOCKAE_IMAGE_BUILD_MAKE_PATH = ${DOCKER_BASE_DIR}/${ENVIRONMENT}/${DOCKER_IMAGE_NAME}

SSM_PARAMETER_PREFIX=/${SERVICE_NAME}/${ENVIRONMENT}
SSM_PARAMETER=${SSM_PARAMETER_PREFIX}/${SSM_PARAMETER_NAME}
